# -*- Makefile -*-
#
# ======================================================================
#
#                           Brad T. Aagaard
#                        U.S. Geological Survey
#
# {LicenseText}
#
# ======================================================================
#

# Note: If the files ARCH.def and ARCH-COMPILER.def do not already
# exist, make a new file that works for you and then please send me
# the files so that I can add them to the repository.

# SET ARCHITECTURE
ARCH = linux

# SET COMPILER FAMILY
COMPILER = gcc-3.x

# DIRECTORY TO HOLD TEMPORARY FILES (object files, dependency files)
BLD_ROOT = $(SRC_TOP)/buildtmp

# DIRECTORY WHERE STUFF WILL BE "INSTALLED"
EXPORT_ROOT = /home/tools/cencalvm

# ----------------------------------------------------------------------
# YOU SHOULDN'T NEED TO EDIT ANYTHING BELOW THIS LINE
# ----------------------------------------------------------------------

include $(CONFIG_DIR)/$(ARCH).def
include $(CONFIG_DIR)/$(ARCH)-$(COMPILER).def
include $(CONFIG_DIR)/variables.def

include Make.mm
include $(CONFIG_DIR)/rules.def

# version
# $Id$

# End of file 
