# -*- Makefile -*-
#
# ======================================================================
#
#                           Brad T. Aagaard
#                        U.S. Geological Survey
#
# {LicenseText}
#
# ======================================================================
#

ARCH = linux

COMPILER = gcc

BLD_ROOT = $(SRC_TOP)/buildtmp
EXPORT_ROOT = /home/tools/cencalvm



include $(CONFIG_DIR)/$(ARCH).def
include $(CONFIG_DIR)/$(ARCH)-$(COMPILER).def
include $(CONFIG_DIR)/variables.def

include Make.mm
include $(CONFIG_DIR)/rules.def

# version
# $Id$

# End of file 
