# -*- Makefile -*-
#
# ======================================================================
#
#                           Brad T. Aagaard
#                        U.S. Geological Survey
#
# {LicenseText}
#
# ======================================================================
#

# Note: If the files os/ARCH.def and compiler/COMPILER/*.def do not already
# exist, make a new file that works for you and then please send me
# the files so that I can add them to the repository.

# SET ARCHITECTURE
ARCH = Darwin

# SET COMPILER FAMILY
COMPILER = gcc-3.x-Darwin

# ABSOLUTE PATH TO DIRECTORY TO HOLD FILES (object files, dependency files)
BLD_ROOT = $(HOME)/src/cencalvm-0.1/buildtmp

# ----------------------------------------------------------------------
# YOU SHOULDN'T EDIT ANYTHING BELOW THIS LINE
# ----------------------------------------------------------------------

include $(CONFIG_DIR)/os/$(ARCH).def
include $(CONFIG_DIR)/compiler/$(COMPILER)/c.def
include $(CONFIG_DIR)/compiler/$(COMPILER)/cpp.def
include $(CONFIG_DIR)/compiler/$(COMPILER)/f77.def
include $(CONFIG_DIR)/variables.def

include Make.mm
include $(CONFIG_DIR)/rules.def

# version
# $Id$

# End of file 
