# -*- Makefile -*-
#
# ======================================================================
#
#                           Brad T. Aagaard
#                        U.S. Geological Survey
#
# {LicenseText}
#
# ======================================================================
#
SRC_TOP = ../../../..
CONFIG_DIR = $(SRC_TOP)/config

include $(CONFIG_DIR)/Makefile.config

# version
# $Id$

# End of file 
